POST http://127.0.0.1:3000/api/register HTTP/1.1
content-type: application/json

{
	"name": "helloooo1",
    "email":"helloooo1@gmail.com",
    "password": "hashedPassword1"
}

###


POST http://127.0.0.1:3000/api/login HTTP/1.1
content-type: application/json

{
    "email":"helloooo1@gmail.com",
    "password": "hashedPassword1"
}
### employee api

GET  http://127.0.0.1:3000/api/emp HTTP/1.1
content-type: application/json
###emp list


GET  http://127.0.0.1:3000/api/dashboard/settings HTTP/1.1
content-type: application/json
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZDMzZWI3OWVkNDY0NjIzM2M5YjZkNGEiLCJpYXQiOjE1NjM2ODQwNTh9.XBS4HHLPZIchgAUIuA3vOTVUnG98Y2JEFS3AjK43Uzc
